name: "csd-if"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 64
  height: 64
  camera_distance_range: [1.5, 2.0]
  fovy_range: [40, 70]
  elevation_range: [-10, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  light_position_perturb: 0.1
  light_distance_range: [1.5, 2.0]
  eval_camera_distance: 2.0
  eval_fovy_deg: 70.
  batch_uniform_azimuth: false
  n_val_views: 120
  front_back_only_iters: 1000

system_type: "magic3d-system"
system:
  geometry_type: "implicit-volume"
  geometry:
    radius: 1.0
    normal_type: "analytic"
    # use Magic3D density initialization instead
    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 12
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.3703509847201236 # max resolution 512

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 5001
    soft_shading: false
    diffuse_prob: 0.5
    textureless_prob: 1.0
    eval_show_albedo: true
    textureless_normal: true

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    estimator: occgrid
    num_samples_per_ray: 512
    return_comp_normal: true

  prompt_processor_type: "deep-floyd-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    use_view_dependent_negative_prompt: false
    prompt: ???
    negative_prompt: "oversaturated color, ugly, tiling, low quality, noisy"
    use_perp_neg: true
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "deep-floyd-simple-guidance"
  guidance:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    weighting_strategy: uniform
    min_step_percent: 0.02
    max_step_percent: [5000, 0.98, 0.5, 5001]
    cond_scale: 1.0
    uncond_scale: [0, -0.0, -1, 5000]
    null_scale: [0, -1, 0.0, 5000]
    noise_scale: 0.
    perpneg_scale: 3.

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 1.
    lambda_orient: [0, 1., 100., 5000]
    lambda_normal_smoothness_2d: 0.
    lambda_sparsity: [0, 10., 1., 5000]
    lambda_opaque: 0.
  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 1.e-15

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 2000
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}