name: "csd-sd-refine"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [1.5, 2.0]
  fovy_range: [40, 70]
  elevation_range: [-10, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  light_position_perturb: 0.1
  light_distance_range: [1.5, 2.0]
  eval_camera_distance: 1.5
  eval_fovy_deg: 70.
  batch_uniform_azimuth: false
  n_val_views: 120
  front_back_only_iters: 0

system_type: "magic3d-system"
system:
  refinement: true
  test_background_white: true
  geometry_convert_from: ???
  geometry_convert_inherit_texture: true
  geometry_convert_override:
    isosurface_threshold: 10.
    # TODO: remove outliers
    isosurface_remove_outliers: false
    isosurface_outlier_n_faces_threshold: 0.01
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    radius: 1.0 
    isosurface_resolution: 256
    isosurface_deformable_grid: true
    pos_encoding_config:
      otype: HashGrid
      n_levels: 12 
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.3703509847201236 
    fix_geometry: false # optimize grid sdf and deformation

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 0
    soft_shading: false
    diffuse_prob: 0.5
    textureless_prob: 1.0
    eval_show_albedo: true
    textureless_normal: true

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: gl

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    use_view_dependent_negative_prompt: false
    negative_prompt: "oversaturated color, ugly, tiling, low quality, noisy"
    use_perp_neg: false

  guidance_type: "stable-diffusion-triple-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    min_step_percent: 0.02
    max_step_percent: 0.5
    cond_scale: 1.
    uncond_scale: [0, -1, -0.5, 10000]
    null_scale: [0, 0, -0.5, 10000]
    noise_scale: 0.

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 1.
    lambda_normal_consistency: 1000.
  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 1.e-15

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 2000
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
